"""Generate notes/PHENOMENON_GATE.md draft from Exp03/Exp04 outputs.

Reads tables/Exp03_summary.json + outputs/Exp04/correlation_report.json and
produces a filled report addressing the plan §25 questions. The final GO/STOP
verdict line is computed mechanically; interpretation stays with the agent.
"""
import json
import re
from pathlib import Path

ROOT = Path("/root/autodl-tmp/EviZO-VP/F-LBQ")


def fmt(x, nd=3):
    try:
        return f"{float(x):.{nd}f}"
    except Exception:
        return "n/a"


def main():
    summary = json.loads((ROOT / "tables/Exp03_summary.json").read_text())
    report = json.loads((ROOT / "outputs/Exp04/correlation_report.json").read_text())
    fp = summary.get("fp") or {}
    rows = summary["rows"]
    corr = report["correlations"]

    c_all = corr.get("feat_rel_mse_all__dAP", {})
    c_b6 = corr.get("bits6__rel_mse_all__dAP", {})
    c_b4 = corr.get("bits4__rel_mse_all__dAP", {})
    c_s = corr.get("feat_rel_mse_all__dAP_S", {})
    c_m = corr.get("feat_rel_mse_all__dAP_M", {})
    c_l = corr.get("feat_rel_mse_all__dAP_L", {})

    sp = c_all.get("spearman", float("nan"))
    kt = c_all.get("kendall", float("nan"))
    n_inv = report.get("n_rank_inversions", 0)
    n_pairs = report.get("n_matched_pairs", 0)
    n_pairs_big = report.get("n_matched_pairs_dap_gt2", 0)

    stop_condition = (sp >= 0.8) and (kt >= 0.7) and (n_pairs_big == 0)
    verdict = "STOP (proxy is good)" if stop_condition else "GO-candidate (mismatch exists) — proceed to diagnosis"

    # sort rows by dAP desc for the worst cases table
    rows_pp = [r for r in rows if r.get("group") != "FP" and "dAP" in r]
    by_dap = sorted(rows_pp, key=lambda r: -r["dAP"])[:8]
    by_mse = sorted(rows_pp, key=lambda r: -r.get("feat_rel_mse_all", 0))[:8]

    lines = []
    L = lines.append
    L("# Phenomenon Gate — F-LBQ proxy reliability audit")
    L("")
    L("Generated by `src/diagnostics/make_gate_report.py` from machine outputs.")
    L("")
    L(f"FP baseline (probe512, bbox AP as fraction): {json.dumps(fp)}")
    L("")
    L("## 1. Rank correlation: D_feat vs ΔAP (all (l,b) points)")
    L("")
    L("| slice | n | Spearman | Kendall | Pearson |")
    L("|---|---|---|---|---|")
    for name, c in [("all", c_all), ("b=6", c_b6), ("b=4", c_b4),
                    ("ΔAP_S", c_s), ("ΔAP_M", c_m), ("ΔAP_L", c_l)]:
        L(f"| {name} | {c.get('n','')} | {fmt(c.get('spearman'))} | {fmt(c.get('kendall'))} | {fmt(c.get('pearson'))} |")
    L("")
    L("## 2. Per-scale answers")
    L(f"- AP_S vs D_feat: Spearman {fmt(c_s.get('spearman'))}")
    L(f"- AP_M vs D_feat: Spearman {fmt(c_m.get('spearman'))}")
    L(f"- AP_L vs D_feat: Spearman {fmt(c_l.get('spearman'))}")
    L("")
    L("## 3. Matched-distortion pairs (|ΔD|/max < 10%)")
    L(f"- total pairs: {n_pairs}, with ΔAP > 2.0 points: {n_pairs_big}")
    L("")
    L("| # | pair | mse_i | mse_j | ΔAP_i | ΔAP_j | ΔAP gap |")
    L("|---|---|---|---|---|---|---|")
    for p in report.get("matched_pairs", [])[:8]:
        L(f"| | {p['i']} vs {p['j']} | {fmt(p['mse_i'],5)} | {fmt(p['mse_j'],5)} | {fmt(p['dap_i'],2)} | {fmt(p['dap_j'],2)} | {fmt(p['dap_diff'],2)} |")
    L("")
    L("## 4. Sensitivity-ordering inversions (clear MSE gap >5%, ΔAP gap >0.5)")
    L(f"- count: {n_inv}")
    L("")
    L("| # | pair | mse_i | mse_j | ΔAP_i | ΔAP_j |")
    L("|---|---|---|---|---|---|")
    for p in report.get("rank_inversions", [])[:8]:
        L(f"| | {p['i']} vs {p['j']} | {fmt(p['mse_i'],5)} | {fmt(p['mse_j'],5)} | {fmt(p['dap_i'],2)} | {fmt(p['dap_j'],2)} |")
    L("")
    L("## Worst damage points (top ΔAP)")
    L("")
    L("| run | group | bits | rel_mse_all | ΔAP |")
    L("|---|---|---|---|---|")
    for r in by_dap:
        L(f"| {r['tag']} | {r.get('group')} | {r.get('bits')} | {fmt(r.get('feat_rel_mse_all'),6)} | {fmt(r['dAP'],2)} |")
    L("")
    L("## Highest feature distortion points")
    L("")
    L("| run | group | bits | rel_mse_all | ΔAP |")
    L("|---|---|---|---|---|")
    for r in by_mse:
        L(f"| {r['tag']} | {r.get('group')} | {r.get('bits')} | {fmt(r.get('feat_rel_mse_all'),6)} | {fmt(r['dAP'],2)} |")
    L("")
    L("## Mechanical verdict (plan §25 STOP condition)")
    L("")
    L(f"STOP requires: Spearman>=0.8 AND Kendall>=0.7 AND no obvious matched-MSE rank inversion.")
    L(f"Observed: Spearman={fmt(sp)}, Kendall={fmt(kt)}, matched pairs with ΔAP>2: {n_pairs_big}.")
    L("")
    L(f"Mechanical result: **{verdict}**")
    L("")
    L("Interpretation and final decision: [AGENT — fill after reading §1-4 + scatter figure]")

    out = ROOT / "notes/PHENOMENON_GATE.md"
    out.write_text("\n".join(lines) + "\n")
    print("written:", out)
    print("mechanical:", verdict)


if __name__ == "__main__":
    main()
